steps:
  - label: "node setup"
    command: "nvm install 14.16.0 && npm install && npm i fibers"
    key: build

  - label: ":test_tube: Test"
    command: "npm run bstack-single"
    key: test
    depends_on: build
