steps:
  - label: "node setup"
    command: "node -v && npm install && npm i fibers"
    key: build

  - label: ":test_tube: Test"
    command: "npm run bstack-single"
    key: test
    depends_on: build
